# fly.toml app configuration file generated for discord-poll-bot on 2025-09-17T19:50:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-poll-bot'
primary_region = 'waw'

[build]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[processes]
  app = "python bot.py"

[restart]
  policy = "always"
